### ISSUE TITLE
breaks discord emojis

### ISSUE THREAD

**Issue by TheKfcBandit** [DavidNyan10/UnicodeFractions#1]
when i click them it just doesnt do anything

**Comment by quincynyan** [comment]
It's working perfectly fine with discord emojis on my end. Please clarify what you mean by "breaks". Also, make sure another plugin isn't conflicting. Check the console (ctrl shift i) to see the errors.

**Comment by TheKfcBandit** [comment]
> It's working perfectly fine with discord emojis on my end. Please clarify what you mean by "breaks". Also, make sure another plugin isn't conflicting. Check the console (ctrl shift i) to see the errors.

I don't know I couldn't use emojis. like when I clicked them it just wouldn't do anything. I tried removing all other plugins except built in and it still didn't work. also tried replugging. no related errors in console

**Comment by quincynyan** [comment]
This is a known issue on Powercord and doesn't have anything to do with my plugin. 

<br/>

Some other things wrong with Canary right now:

- Quick switcher takes you to support page
- Can't click search box
- CSS of images are so broken
- And probly some more as Discord is drunk rn

If you have any more comments (suggestions/issues), feel free to create another issue.

**Comment by quincynyan** [comment]
Sorry, it seems like the plugin _is_ the issue. Something's wrong with the injection. I'll look into it and reopen this issue.

**Comment by quincynyan** [comment]
As of right now, here're the known issues that the plugin breaks:

- Emojis (can't click on them on the emoji selection box)
- Selection of texts (can't select text in messages)
- Search bar (can't click on the search bar)
- Quick switcher (takes you to the support page instead of taking you to the last channel)

I'll try to provide a fix for this, but for now, you can temporarily (like for 5 seconds) fix this by right-clicking on a message (any messages) before you use emojis or select texts or use quick switcher or the search bar. 

It seems that the injection is broken. Most plugins inject into `sendMessage` but it doesn't work when you upload files, as another method is called when you send a message with attachments. This plugin fixes it by doing a different injection which works when you upload images but apparently, it also breaks these things above. I'll revert back to the old `sendMessage` injection where these will be fixed, but doing so will make UnicodeFractions not available when you send messages with attachments (They won't convert the fractions when you upload files). I'll try to find a fix for that, and thank you for opening an issue and helping me out!

**Comment by quincynyan** [comment]
I have pushed v1.0.3 which should work now.

**Comment by quincynyan** [comment]
I'll be closing this for now but you can reopen the issue if you have any more comments.
