### ISSUE TITLE
Message Highlight issues

### ISSUE THREAD

**Issue by MintLily** [DavidNyan10/UnicodeFractions#2]
Having this plugin enabled causes me to not be able to highlight content in messages. Disabling the plugin allows me to highlight content again.

Just in case you need my active plugins:
Powercord: <I>Note: not all plugins are toggled on</i><br>
<details>
    <summary>Expand</summary>
    <img src="https://i.mintlily.lgbt/KoMPKqVevA4Z.png" alt="Powercord Plugins" />
</details>

**Comment by quincynyan** [comment]
It seems like a problem with the injection. Thank you, I'll look into it.

**Comment by quincynyan** [comment]
As of right now, here're the known issues that the plugin breaks:

- Emojis (can't click on them on the emoji selection box)
- Selection of texts (can't select text in messages)
- Search bar (can't click on the search bar)
- Quick switcher (takes you to the support page instead of taking you to the last channel)

I'll try to provide a fix for this, but for now, you can temporarily (like for 5 seconds) fix this by right-clicking on a message (any messages) before you use emojis or select texts or use quick switcher or the search bar. 

It seems that the injection is broken. Most plugins inject into `sendMessage` but it doesn't work when you upload files, as another method is called when you send a message with attachments. This plugin fixes it by doing a different injection which works when you upload images but apparently, it also breaks these things above. I'll revert back to the old `sendMessage` injection where these will be fixed, but doing so will make UnicodeFractions not available when you send messages with attachments (They won't convert the fractions when you upload files). I'll try to find a fix for that, and thank you for opening an issue and helping me out!

**Comment by quincynyan** [comment]
I have pushed v1.0.3 which should work now.

**Comment by quincynyan** [comment]
I'll be closing this for now but you can reopen the issue if you have any more comments.
